export const  hostelDetails = {
  all: [
    "Ladies' Hostel - A Block",
    "Ladies' Hostel - B Block",
    "Ladies' Hostel - C Block",
    "Ladies' Hostel - D Block",
    "Ladies' Hostel - E Block",
    "Ladies' Hostel - F Block",
    "Ladies' Hostel - G Block",
    "Ladies' Hostel - H Block",
    "Men's Hostel - A Block",
    "Men's Hostel - B Block",
    "Men's Hostel - B Annex",
    "Men's Hostel - C Block",
    "Men's Hostel - D Block",
    "Men's Hostel - D Annex",
    "Men's Hostel - E Block",
    "Men's Hostel - F Block",
    "Men's Hostel - G Block",
    "Men's Hostel - H Block",
    "Men's Hostel - J Block",
    "Men's Hostel - K Block",
    "Men's Hostel - L Block",
    "Men's Hostel - M Block",
    "Men's Hostel - N Block",
    "Men's Hostel - P Block",
    "Men's Hostel - Q Block",
    "Men's Hostel - R Block",
  ],
  mens: [
    "Men's Hostel - A Block",
    "Men's Hostel - B Block",
    "Men's Hostel - B Annex",
    "Men's Hostel - C Block",
    "Men's Hostel - D Block",
    "Men's Hostel - D Annex",
    "Men's Hostel - E Block",
    "Men's Hostel - F Block",
    "Men's Hostel - G Block",
    "Men's Hostel - H Block",
    "Men's Hostel - J Block",
    "Men's Hostel - K Block",
    "Men's Hostel - L Block",
    "Men's Hostel - M Block",
    "Men's Hostel - N Block",
    "Men's Hostel - P Block",
    "Men's Hostel - Q Block",
    "Men's Hostel - R Block",
  ],
  ladies: [
    "Ladies' Hostel - A Block",
    "Ladies' Hostel - B Block",
    "Ladies' Hostel - C Block",
    "Ladies' Hostel - D Block",
    "Ladies' Hostel - E Block",
    "Ladies' Hostel - F Block",
    "Ladies' Hostel - G Block",
    "Ladies' Hostel - H Block",
  ],
};
